apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.container.name.default}}"
  labels:
    name: "{{.Values.container.name.default}}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  type: NodePort
  ports:
  - name: pgsql
    port: {{.Values.container.port}}
    targetPort: {{.Values.container.port}}
    nodePort: 31432
    protocol: TCP
  selector:
    app: "{{.Values.container.name.default}}"
